### ISSUE TITLE
wifi-pineapple-war-driver on Tetra Pineapple

### ISSUE THREAD

**Issue by pavetrck** [sailboat-anon/wifi-pineapple-war-driver#1]
Hi, is it possible to run this script on older Pineapple Tetra somehow? Thx.

**Comment by sailboat-anon** [comment]
Hello, friend.  I'm utilizing the [Hak5 REST API](https://docs.hak5.org/hc/en-us/articles/360049854174-WiFi-Pineapple-Mark-VII-REST-API), but I'm not sure if it's in the Tetra firmware.  Could you give it a try and let me know?  Assuming it uses the API, my code is to their standard so there shouldn't be issues.
