### ISSUE TITLE
Error on Kali 2021

### ISSUE THREAD

**Issue by ghost** [sailboat-anon/wifi-pineapple-war-driver#2]
This is what I get on KALI, all is configured:

└─$ php war-driver.php 
> Starting war-driver.php by sailboatanon
> https://github.com/sailboat-anon/ 
> Enabling pineAP (AGGRO settings)
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/jd/wifi-pineapple-war-driver/war-driver.php:149
Stack trace:
#0 /home/jd/wifi-pineapple-war-driver/war-driver.php(190): authenticate()
#1 /home/jd/wifi-pineapple-war-driver/war-driver.php(63): authorized_put()
#2 /home/jd/wifi-pineapple-war-driver/war-driver.php(67): set_aggro()
#3 /home/jd/wifi-pineapple-war-driver/war-driver.php(43): run_scand()
#4 {main}
  thrown in /home/jd/wifi-pineapple-war-driver/war-driver.php on line 149

**Comment by ghost** [comment]
Arrghhh, I did not have php_curl activated...    Maybe put that in the Readme.

**Comment by sailboat-anon** [comment]
Sorry, mate.  I'm going to dockerize this and make it even simpler.  Thank you!
