### ISSUE TITLE
Throwing errors for stdClass

### ISSUE THREAD

**Issue by Paddy-Wa** [sailboat-anon/wifi-pineapple-war-driver#3]
Suspect it may be something I'm doing wrong, but when I run this app on my Kali box it connects, and sets PineAP settgins and performs the scan but each entry with Clients falls over on line 101 and 102 with these errors. Please advise.

> Found AP with clients (04:xx:xx:xx:xx:50)
PHP Notice:  Undefined property: stdClass::$Int64 in /war-driver.php on line 101
PHP Notice:  Undefined property: stdClass::$Valid in /war-driver.php on line 102

**Comment by sailboat-anon** [comment]
Hello.  These are just warnings and will not affect the functionality at all.  It appears the data model changed slightly.  I'm writing the next version of the app soon and will be dockerized and have a much nicer user interface.

**Comment by nathanhatesjelly** [comment]
was a solution ever found for this issue or did you ever write a new version of the app

because after i get that error i then get 

cURL Error: Empty reply from server
